### PR TITLE
Add map reduce and filter methods

### PR DESCRIPTION
**Pull request by geiseri**
This is the first whack at #7.  So far reduce is in place and tested.  Map and Filter both
have problems with being generic still, but the initial tests pass.  
This needs significant cleanup before it is merged.  I am looking for 
advice on how to solve the `FIXME` issues in the code.

### CODE REVIEW

**Comment by simonbrunel** [comment]
@geiseri Nice work! I think there is an issue with `.filter` which doesn't guarantee the sequence order if `handler` is asynchronous.

I may not merge this PR since I already have a branch with working `filter` and `map` implementations which already addresses your FIXME. It also provides static versions for both + helpers:

```cpp
// statics
template<T, R, Mapper> QPromise<QVector<R>>::map(Sequence<T>, Mapper);
template<T, R, Mapper> QPromise<QVector<R>>::map(Sequence<QPromise<T>>, Mapper);
template<T, R, Filter> QPromise<QVector<T>>::filter(Sequence<T>, Filter);
template<T, R, Filter> QPromise<QVector<T>>::filter(Sequence<QPromise<T>>, Filter);
```

I will try to get a PR before the end of the week, if you are interested in testing / reviewing it.

**Comment by geiseri** [comment]
Actually, I am on a bit of a deadline here so the sooner the better.  I am sure my implementation is pretty rough, but if it can accelerate things I could help.  If nothing else I would like to keep the tests and documentation for the implementation just because it matches my usecase perfectly ;)

If you are game for keeping the test cases I will add a test to validate a guarantee of the sequence order if the handler is asynchronous.

**Comment by simonbrunel** [comment]
@geiseri I can't guarantee that all of these methods will be in master this week, so may be better for you to keep working against your fork until it's fully implemented on my side. 

Would you like to help reviewing my implementation / tests / docs? if so, I will split each of these methods in different PRs, else, I will push to master directly.

**Comment by geiseri** [comment]
I have tests passing again in my local branch.  I merged in your map impl and am refactoring filter and reduce to match the pattern.  I will push that this evening.

**Comment by simonbrunel** [comment]
`map` implement in 69c07855, `filter` and `each` are almost ready.

**Comment by simonbrunel** [comment]
Finally got all these methods implemented:

- each: 051fed5fbc881323bdf87712538c6fc7cf6a4160
- filter: 4fa7a37750e2005af3e8a6d3eee37cfea3647ad0
- map: 69c07855f476a930345d0a5840ea3dfadc296c07
- reduce: d3bd28bab47fc7c63702b4f61bd51ca9a50c577f (with support for promise values and optional initial value)

Thanks @geiseri for your work

**Pull request closed without merging**
