### PR TITLE
Complex Object Assembly from Promises

### PR DESCRIPTION
**Pull request by geiseri**
We have a pattern in our code where we need to create an object from multiple promises because we have to integrate with an existing dbus system.  This may or not be useful to others in a general case, but I figured I would contribute anyway.  In theory, this could solve #9.  It needs more test coverage and documentation yet.

Given:

```cpp
struct Object {
    int field1;
    QString field2;
    ...
    QByteArray fieldN;
};
```

Normally we have a pattern of:

```cpp
QPromise<Object> resolveObject() 
{
    Object result;
    return getField1().then([=](int field1) mutable {
        result.field1 = field1;
        return getField2();
    }).then([=](QString field2) mutable {
        result.field2 = field2;
        return getFieldN();
    })
    ...
    }).then([=](QByteArray fieldN) mutable {
        result.fieldN = fieldN;
        return result;
    })
}
```

With our tuple pattern we can simplify the code to:

```cpp
QPromise<Object> resolveObject() 
{
    return QPromise<Object>::props(
        std::make_tuple(
            getField1(),
            getField2(),
            ...
            getFieldN()
        )
    );
}
```

Advantages:

* Clearer intent of the operations
* Promises can resolve in parallel
* Can handle a mixture of promises or static values

Disadvantages:

* Only works with `struct` types and types with `Initializer Lists`
* Need to make sure the order of the promises tuple and the results the structs all lineup (Seems like magic)
* Exposure of the `std::tuple` to the caller when they shouldn't care

Comments on its usefulness or improvement?

### CODE REVIEW

**Comment by geiseri** [comment]
@simonbrunel what should I do in the case that one of these tests require C++14 or greater? Should I remove the test (since it wouldn't run on CI anyway)?

**Comment by simonbrunel** [comment]
Yes since I would prefer to not introduce c++14 in unit tests

**Comment by geiseri** [comment]
@simonbrunel any thoughts on this?

**Comment by simonbrunel** [comment]
@geiseri Thanks again for your hard work and really sorry for the lack of feedback on this PR. It's a quite complex implementation (especially to be compatible with c++11) and I will need to think deeper about the API I really want to introduce. Unfortunately, I still don't have enough free time to iterate on it but I will keep it in the backlog (#9). I will close this PR but as soon as I can work on this feature, I will probably reuse a lot of your code / documentation.

**Pull request closed without merging**
